### ISSUE TITLE
[FEA] Improve doxygen documentation

### ISSUE THREAD

**Issue by vyasr** [rapidsai/rmm#1368]
**Is your feature request related to a problem? Please describe.**
In the process of working through issues in #1324 we identified a number of improvements that we'd like to see in rmm documentation. This issue attempts to capture those items for future improvements.

**Describe the solution you'd like**

```[tasklist]
### Tasks
- [ ] Add documentation for each doxygen group
- [ ] Add documentation of the rmm namespace
- [ ] Use a better theme for the documentation to improve organization and reduce how cramped it is
- [ ] Improve the ToC and the appearance in the sidebar
```
