### ISSUE TITLE
Deprecate and remove `get_mem_info` methods from memory resources.

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#1388]
`device_memory_resource::get_mem_info` has always been hard to support for arbitrary memory resources. Sometimes it is impossible to calculate and so MRs have another method `supports_get_mem_info()` that returns true if `get_mem_info()` returns useful values.

We are now in the process of adopting `cuda::memory_resource` and `resource_ref` concepts into RMM, and we would like to embrace the flexibility and composability they enable. `cuda::memory_resource` does not provide anything like `get_mem_info()`, just like its inspiration `std::pmr::memory_resource`.

I am now experimenting with defining a `host_pinned_memory_resource` using the `cuda::memory_resource` concept and *not* deriving from `rmm::mr::device_memory_resource`. This works as an upstream for other resources, such as `pool_memory_resource`, except for one detail: `pool_memory_resource` relies on `cudaMemGetInfo` if the initial and maximum pool sizes are not specified, but that function cannot be used for pinned host memory!

I propose that we deprecate and remove the use of `supports_get_mem_info()` and `get_mem_info()`.  For resources like `pool`, I recommend that we change them to NOT query memory sizes and make initial and maximum pool sizes required constructor parameters. While this may seem to make them harder to use, we can expose `rmm::detail::available_device_memory()` (which calls `cudaMemGetInfo`) as a utility in the public interface to use when the user knows the pool is device memory. We may also be able to provide a utility function that estimates host memory available.

Once we move entirely to the `cuda::memory_resource` concept, we will be able to drop the `device_memory_resource` base class and in that way remove the deprecated `get_mem_info` methods.

See also https://github.com/rapidsai/rmm/issues/305

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/rmm/issues/1416
- [ ] https://github.com/rapidsai/rmm/issues/1426
- [ ] https://github.com/rapidsai/rmm/issues/1427
- [ ] https://github.com/rapidsai/rmm/issues/1428
```
