### ISSUE TITLE
Deprecate and remove `supports_streams()` from memory resources

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#1389]
As we move to replace `device_memory_resource` and `host_memory_resource` as dichotomous base classes in favor of the `cuda::memory_resource` concept, I think where possible we should deprecate features of the former that are not part of the interface defined by the latter.

Let's deprecate and remove the little-used `rmm::mr::device_memory_resource::supports_streams()`.
```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/rmm/issues/1432
- [ ] https://github.com/rapidsai/rmm/issues/1433
- [ ] https://github.com/rapidsai/rmm/issues/1434
```
