### ISSUE TITLE
[FEA] Change `rmm::get_current_device_resource`/`set_current_device_resource` to use rmm::device_async_resource_ref

### ISSUE THREAD

**Issue by harrism** [rapidsai/rmm#1596]
This is blocked on design issues. We need to prototype a shared-ownership model for `set_current_Device_resource()` using upcoming `shared_resource` / `any_resource` from CCCL. These classes are only just becoming available in `cudax`.

Once that is working we can design and implement a Cython solution around it. Also, resource adaptors should use a `shared_resource` for their upstream resources. 

```[tasklist]
### Tasks
- [ ] https://github.com/rapidsai/rmm/issues/1597
- [ ] https://github.com/rapidsai/rmm/issues/1660
- [ ] Update RAPIDS repos to use resource_ref versions
- [ ] Deprecate `get_current_device_resource` and related functions
- [ ] Remove `get_current_device_resource` and related functions.
```

**Comment by bdice** [comment]
Closing this as outdated. We're tracking the adoption of the CCCL memory resource design in #2011.
