### ISSUE TITLE
[FEA] Remove factory functions from resource adaptors

### ISSUE THREAD

**Issue by mhaseeb123** [rapidsai/rmm#1616]
Consider removing factory functions with constructors in `prefetch_resource_adaptor`, `statistics_resource_adaptor`, `logging_resource_adaptor` and others in rmm.

More context at: 

>              question: can't this just be a constructor? > Why do we need a factory function?

_Originally posted by @jrhemstad in https://github.com/rapidsai/rmm/pull/1608#discussion_r1674886164_

```[tasklist]
### Tasks
- [x] Change calls to adaptor factories across RAPIDS repos to use constructors
- [ ] https://github.com/rapidsai/rmm/issues/1641
- [ ] Remove deprecated adaptor factories in 24.12
```

**Comment by harrism** [comment]
All of these classes already have constructors. I think what you mean is we should remove the factory functions.

**Comment by bdice** [comment]
I opened two PRs, #1625 and #1626, that should help with this.

**Comment by harrism** [comment]
Added tasklist to this issue.
